<?php
// This file is generated by Composer
require 'blocks/auth.php';
$language = $_POST['lang'];
$search = $_POST['search'];
$repos = $client->api('repo')->find($search, array('language' => $language));
?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php include_once 'blocks/jquery_connect.php'; ?>
        <title>MobiDev </title>
        <link rel="stylesheet" type="text/css" href="style/style.css">

    </head>
    <body>

        <div id="main">

            <div id="search">
                <div style='float: left;'><h3> GitHub Browser >> Search</h3></div>
                <div id="search_form">
                    <?php require_once 'blocks/form.php'; ?>
                </div>
            </div>

            <div id="content">
                <div align='center'>
                    <?php
                    if (isset($search)) {
                        echo "<span>
                       <h2>For search  term '" . $search . "' found :</h2> 
                   </span>";
                    }
                    ?>
                </div>
                <div  id="repo_list">

                    <?php
                    for ($i = 0; $i < 4; $i++) {
                        echo "  <table width='100%' align='center'  CELLPADDING=10 ><tr>
                            <td width='30%'><h3><a href='repo_info.php?repo=" . $repos[repositories][$i][name] . "'>" . $repos[repositories][$i][name] . "</a></h3></td>
                                <td><a href='http://". $repos[repositories][$i][homepage] ."'>". $repos[repositories][$i][homepage] ." </a></td><td width='20%'><a href='user_info?user=". $repos[repositories][$i][owner] . "'>". $repos[repositories][$i][owner] . "</a></td>
                        </tr>
                        <tr>
                            <td>" . $repos[repositories][$i][description] . "</td>
                        </tr>
                        <tr>
                            <td>watchers : " . $repos[repositories][$i][watchers] . "</td><td>forks : " . $repos[repositories][$i][forks] . "</td><td></td><td  align='center' width='10%' ROWSPAN='3'> <span><a  class='like-Unlike' href=' '>Like</a></span></td>
                         </tr>  </table>";
                    }
                    ?>

                </div>

                <?php
                print_r($repos[repositories]);
                echo $repos[repositories][0][username];
                ?>



            </div>


        </div>


    </body>
</html>
